NWS_REGIONS = {"AR": "Alaska Region", "CR": "Central Region", "ER": "Eastern Region",
               "PR": "Pacific Region", "SR": "Southern Region", "WR": "Western Region",
               "NCEP":"National", "HQ":"National"}

NWS_OFFICES = {'ABR - WFO ABERDEEN': 'Central Region',
               'ABRFC - ARKANSAS-RED BASIN (TULSA) RFC': 'Southern Region',
               'AFC - WFO ANCHORAGE': 'Alaska Region',
               'AFG - WFO FAIRBANKS': 'Alaska Region',
               'AJK - WFO JUNEAU': 'Alaska Region',
               'AKQ - WFO WAKEFIELD': 'Eastern Region',
               'ALY - WFO ALBANY': 'Eastern Region',
               'AMA - WFO AMARILLO': 'Southern Region',
               'APRFC - ALASKA PACIFIC (ANCHORAGE) RFC': 'Alaska Region',
               'APX - WFO NORTH CENTRAL LOWER MICHIGAN (GAYLORD)': 'Central Region',
               'ARX - WFO LA CROSSE': 'Central Region',
               'BGM - WFO BINGHAMTON': 'Eastern Region',
               'BIS - WFO BISMARCK': 'Central Region',
               'BMX - WFO BIRMINGHAM': 'Southern Region',
               'BOI - WFO BOISE': 'Western Region',
               'BOU - WFO DENVER/BOULDER': 'Central Region',
               'BOX - WFO BOSTON (TAUNTON)': 'Eastern Region',
               'BRO - WFO BROWNSVILLE': 'Southern Region',
               'BTV - WFO BURLINGTON': 'Eastern Region',
               'BUF - WFO BUFFALO': 'Eastern Region',
               'BYZ - WFO BILLINGS': 'Western Region',
               'CAE - WFO COLUMBIA': 'Eastern Region',
               'CAR - WFO CARIBOU': 'Eastern Region',
               'CBRFC - COLORADO BASIN (SALT LAKE CITY) RFC': 'Western Region',
               'CHS - WFO CHARLESTON (SC)': 'Eastern Region',
               'CLE - WFO CLEVELAND': 'Eastern Region',
               'CNRFC - CALIFORNIA-NEVADA (SACRAMENTO) RFC': 'Western Region',
               'CRP - WFO CORPUS CHRISTI': 'Southern Region',
               'CTP - WFO CENTRAL PA (STATE COLLEGE)': 'Eastern Region',
               'CYS - WFO CHEYENNE': 'Central Region',
               'DDC - WFO DODGE CITY': 'Central Region',
               'DLH - WFO DULUTH': 'Central Region',
               'DMX - WFO DES MOINES (JOHNSTON)': 'Central Region',
               'DTX - WFO DETROIT (WHITE LAKE)': 'Central Region',
               'DVN - WFO QUAD CITIES (DAVENPORT)': 'Central Region',
               'EAX - WFO KANSAS CITY (PLEASANT HILL)': 'Central Region',
               'EKA - WFO EUREKA': 'Western Region',
               'EPZ - WFO EL PASO WFO (SANTA TERESA)': 'Southern Region',
               'EWX - WFO AUSTIN/SAN ANTONIO (NEW BRAUNFELS)': 'Southern Region',
               'EYW - WFO KEY WEST WFO FLORIDA': 'Southern Region',
               'FFC - WFO ATLANTA (PEACHTREE CITY)': 'Southern Region',
               'FGF - WFO EASTERN NORTH DAKOTA (GRAND FORKS)': 'Central Region',
               'FGZ - WFO FLAGSTAFF': 'Western Region',
               'FSD - WFO SIOUX FALLS': 'Central Region',
               'FWD - WFO FORT WORTH/DALLAS': 'Southern Region',
               'GGW - WFO GLASGOW': 'Western Region',
               'GID - WFO GRAND ISLAND (HASTINGS)': 'Central Region',
               'GJT - WFO GRAND JUNCTION': 'Central Region',
               'GLD - WFO GOODLAND': 'Central Region',
               'GRB - WFO GREEN BAY': 'Central Region',
               'GRR - WFO GRAND RAPIDS': 'Central Region',
               'GSP - WFO GREENVILLE-SPARTANBURG': 'Eastern Region',
               'GUM - WFO GUAM (BARRIGADA)': 'Pacific Region',
               'GYX - WFO PORTLAND (GRAY)': 'Eastern Region',
               'HFO - WFO HONOLULU': 'Pacific Region',
               'HGX - WFO HOUSTON (DICKINSON)': 'Southern Region',
               'HNX - WFO SAN JOAQUIN VALLEY (HANFORD)': 'Western Region',
               'HUN - WFO HUNTSVILLE': 'Southern Region',
               'ICT - WFO WICHITA': 'Central Region',
               'ILM - WFO WILMINGTON (NC)': 'Eastern Region',
               'ILN - WFO CINCINNATI (WILMINGTON)': 'Eastern Region',
               'ILX - WFO CENTRAL ILLINOIS (LINCOLN)': 'Central Region',
               'IND - WFO INDIANAPOLIS': 'Central Region',
               'IWX - WFO NORTHERN INDIANA (NORTH WEBSTER)': 'Central Region',
               'JAN - WFO JACKSON': 'Southern Region',
               'JAX - WFO JACKSONVILLE': 'Southern Region',
               'JKL - WFO JACKSON': 'Central Region',
               'LBF - WFO NORTH PLATTE': 'Central Region',
               'LCH - WFO LAKE CHARLES WFO LOUISIANA': 'Southern Region',
               'LIX - WFO NEW ORLEANS/BATON ROUGE (SLIDELL)': 'Southern Region',
               'LKN - WFO ELKO': 'Western Region',
               'LMK - WFO LOUISVILLE': 'Central Region',
               'LMRFC - LOWER MISSISSIPPI (SLIDELL) RFC': 'Southern Region',
               'LOT - WFO CHICAGO (ROMEOVILLE)': 'Central Region',
               'LOX - WFO LOS ANGELES (OXNARD)': 'Western Region',
               'LSX - WFO ST. LOUIS (ST. CHARLES)': 'Central Region',
               'LUB - WFO LUBBOCK WFO TEXAS': 'Southern Region',
               'LWX - WFO BALTIMORE/WASHINGTON (STERLING)': 'Eastern Region',
               'LZK - WFO LITTLE ROCK WFO ARKANSAS': 'Southern Region',
               'MAF - WFO MIDLAND WFO TEXAS': 'Southern Region',
               'MARFC - MIDDLE ATLANTIC (STATE COLLEGE) RFC': 'Eastern Region',
               'MBRFC - MISSOURI BASIN (PLEASANT HILL) RFC': 'Central Region',
               'MEG - WFO MEMPHIS WFO TENNESSEE': 'Southern Region',
               'MFR - WFO MEDFORD': 'Western Region',
               'MHX - WFO MOREHEAD CITY (NEWPORT)': 'Eastern Region',
               'MIA - WFO MIAMI WFO FLORIDA': 'Southern Region',
               'MKX - WFO MILWAUKEE (SULLIVAN)': 'Central Region',
               'MLB - WFO MELBOURNE WFO FLORIDA': 'Southern Region',
               'MOB - WFO MOBILE WFO ALABAMA': 'Southern Region',
               'MPX - WFO MINNEAPOLIS (CHANHASSEN)': 'Central Region',
               'MQT - WFO MARQUETTE': 'Central Region',
               'MRX - WFO KNOXVILLE/TRI-CITIES (MORRISTOWN)': 'Southern Region',
               'MSO - WFO MISSOULA': 'Western Region',
               'MTR - WFO SAN FRANCISCO BAY AREA (MONTEREY)': 'Western Region',
               'NCRFC - NORTH CENTRAL (CHANHASSEN) RFC': 'Central Region',
               'NERFC - NORTHEAST (TAUNTON) RFC': 'Eastern Region',
               'NWRFC - NORTHWEST (PORTLAND) RFC': 'Western Region',
               'OAX - WFO OMAHA (VALLEY)': 'Central Region',
               'OHRFC - OHIO (WILMINGTON) RFC': 'Eastern Region',
               'OHX - WFO NASHVILLE (OLD HICKORY)': 'Southern Region',
               'OKX - WFO NEW YORK (UPTON)': 'Eastern Region',
               'OTX - WFO SPOKANE': 'Western Region',
               'OUN - WFO OKLAHOMA CITY/NORMAN': 'Southern Region',
               'PAH - WFO PADUCAH': 'Central Region',
               'PBZ - WFO PITTSBURGH': 'Eastern Region',
               'PDT - WFO PENDLETON': 'Western Region',
               'PHI - WFO PHILADELPHIA (MT. HOLLY)': 'Eastern Region',
               'PIH - WFO POCATELLO': 'Western Region',
               'PQR - WFO PORTLAND': 'Western Region',
               'PSR - WFO PHOENIX': 'Western Region',
               'PUB - WFO PUEBLO': 'Central Region',
               'RAH - WFO RALEIGH': 'Eastern Region',
               'REV - WFO RENO': 'Western Region',
               'RIW - WFO RIVERTON': 'Central Region',
               'RLX - WFO CHARLESTON (WV)': 'Eastern Region',
               'RNK - WFO ROANOKE (BLACKSBURG)': 'Eastern Region',
               'SERFC - SOUTHEAST (PEACHTREE CITY) RFC': 'Southern Region',
               'SEW - WFO SEATTLE': 'Western Region',
               'SGF - WFO SPRINGFIELD': 'Central Region',
               'SGX - WFO SAN DIEGO': 'Western Region',
               'SHV - WFO SHREVEPORT': 'Southern Region',
               'SJT - WFO SAN ANGELO': 'Southern Region',
               'SJU - WFO SAN JUAN (CAROLINA) PR': 'Southern Region',
               'SLC - WFO SALT LAKE CITY': 'Western Region',
               'STO - WFO SACRAMENTO': 'Western Region',
               'TBW - WFO TAMPA BAY AREA (RUSKIN)': 'Southern Region',
               'TFX - WFO GREAT FALLS': 'Western Region',
               'TLH - WFO TALLAHASSEE': 'Southern Region',
               'TOP - WFO TOPEKA': 'Central Region',
               'TSA - WFO TULSA': 'Southern Region',
               'TWC - WFO TUCSON': 'Western Region',
               'UNR - WFO RAPID CITY': 'Central Region',
               'VEF - WFO LAS VEGAS': 'Western Region',
               'WGRFC - WEST GULF (FORT WORTH) RFC': 'Southern Region',
               'ZAB - ALBUQUERQUE CWSU': 'Southern Region',
               'ZAN - ALASKA (ANCHORAGE) CWSU': 'Alaska Region',
               'ZAU - AURORA CWSU': 'Central Region',
               'ZBW - NASHUA (BOSTON) CWSU': 'Eastern Region',
               'ZDC - LEESBURG (WASHINGTON DC) CWSU': 'Eastern Region',
               'ZDV - LONGMONT CWSU': 'Central Region',
               'ZFW - FORT WORTH CWSU': 'Southern Region',
               'ZHU - HOUSTON CWSU': 'Southern Region',
               'ZID - INDIANAPOLIS CWSU': 'Central Region',
               'ZJX - JACKSONVILLE CWSU': 'Southern Region',
               'ZKC - OLATHE CWSU': 'Central Region',
               'ZLA - PALMDALE CWSU': 'Western Region',
               'ZLC - SALT LAKE CITY CWSU': 'Western Region',
               'ZMA - MIAMI CWSU': 'Southern Region',
               'ZME - MEMPHIS CWSU': 'Southern Region',
               'ZMP - FARMINGTON CWSU': 'Central Region',
               'ZNY - ISLIP (NEW YORK) CWSU': 'Eastern Region',
               'ZOA - FREMONT CWSU': 'Western Region',
               'ZOB - OBERLIN (CLEVELAND) CWSU': 'Eastern Region',
               'ZSE - AUBURN CWSU': 'Western Region',
               'ZTL - ATLANTA CWSU': 'Southern Region',
               'AR-ROC - ALASKA REGION ROC': 'Alaska Region',
               'CR-ROC - CENTRAL REGION ROC': 'Central Region',
               'ER-ROC - EASTERN REGION ROC': 'Eastern Region',
               'PR-ROC - PACIFIC REGION ROC': 'Pacific Region',
               'SR-ROC - SOUTHERN REGION ROC': 'Southern Region',
               'WR-ROC - WESTERN REGION ROC': 'Western Region',
               'OTHER - OTHER - HEADQUARTERS/NATIONAL': 'National'}







